---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-langop-io-v1alpha1-languageagent
  failurePolicy: Fail
  name: mlanguageagent.kb.io
  rules:
  - apiGroups:
    - langop.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - languageagents
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-langop-io-v1alpha1-languageagent
  failurePolicy: Fail
  name: vlanguageagent.kb.io
  rules:
  - apiGroups:
    - langop.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - languageagents
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-langop-io-v1alpha1-languagecluster
  failurePolicy: Fail
  name: vlanguagecluster.kb.io
  rules:
  - apiGroups:
    - langop.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - languageclusters
  sideEffects: None
