apiVersion: v1
kind: Service
metadata:
  name: {{ include "language-operator.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "language-operator.labels" . | nindent 4 }}
    {{- with .Values.serviceLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: https
    port: {{ .Values.service.metricsPort }}
    protocol: TCP
    targetPort: metrics
  selector:
    {{- include "language-operator.selectorLabels" . | nindent 4 }}
